[package]
name = "eventcore-testing"
version = "0.1.0"
edition = "2024"

[lints.rust]
warnings = "deny"

[dependencies]
eventcore = { path = ".." }
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
